<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Precision_Engineering.BusinessLogic</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="D:\Projects\Pricison Engineering\Precision Engineering\Precision Engineering.BLL\Jwt Token\JwtServise.cs" Link="JwtServise.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Precision Engineering.DAL\Precision Engineering.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Jwt Token\" />
  </ItemGroup>

</Project>
